export const formSchema = {
  menuId: 14,
  postUrl: "/contacts",
  buttonName: "Customer",
  sheetTitle: "Add New Customer",
  sheetDescription: "",
  fields: [
    {
      label: "Name",
      name: "name",
      type: "text",
      required: true,
      error: "Name field is required",
      validations: [
        {
          min: 3,
          message: "Should have min 3 characters",
        },
        {
          max: 100,
          message: "Should not have more than 100 characters",
        },
      ],
    },
    {
      label: "Mobile Number",
      name: "mobile",
      type: "text",
      required: true,
      error: "Mobile number is required",
      validations: [
        {
          min: 10,
          message: "Should have min 10 digits",
        },
        {
          max: 12,
          message: "Should have max 12 digits",
        },
      ],
    },
    {
      label: "Date of Birth",
      name: "birthDate",
      type: "date",
      required: false,
      error: "Date of birth is required",
      validations: [],
    },
    {
      label: "Email Id",
      name: "email",
      type: "email",
      required: false,
      error: "",
      validations: [],
    },
    {
      label: "Select Contact Type",
      name: "contactType",
      type: "select",
      optionsAPI: "/contact-types",
      required: true,
      defaultValue: 1,
      readOnly: true,
      error: "Please select a contact type",
      validations: [],
    },
    {
      label: "Select Country",
      name: "country",
      type: "select",
      optionsAPI: "/countries",
      required: false,
      defaultValue: 101,
      readOnly: true,
      error: "",
      validations: [],
    },
    // {
    //   label: "Select State",
    //   name: "state",
    //   type: "select",
    //   optionsAPI: "/states",
    //   required: false,
    //   readOnly: true,
    //   error: "",
    //   validations: [],
    // },
    // {
    //   label: "Select City",
    //   name: "city",
    //   type: "select",
    //   readOnly: true,
    //   required: false,
    //   optionsAPI: "/cities",
    //   error: "",
    //   validations: [],
    // },
    {
      label: "Is InActive",
      name: "isInactive",
      type: "checkbox",
      required: false,
      defaultValue: false,
      error: "",
      validations: [],
    },
  ],
};
